// =====================================================================
// MODL-1101 — Étape 2 (2nd midterm) · Le monde étudiant
// Merged from etape2_part1.js (Classes 7-9) + etape2_part2.js (Class 10)
// =====================================================================

window.ETAPE_DATA = {
  vocab: [
    // ==================================================================
    // PART 1: Classes 7-9 (classroom additions, useful, identify, alphabet,
    //          calendar, numbers, time, subjects, avoir)
    // ==================================================================
    // ===== CLASSROOM OBJECTS — Étape 2 additions (Page 22, 32) =====
    {en:"a notebook",                  fr:"un cahier",            alts:["un cahier"],            needsHyphen:false, needsAccent:false, gender:"m", guessGender:true, category:"classroom"},
    {en:"a pencil",                    fr:"un crayon",            alts:["un crayon"],            needsHyphen:false, needsAccent:false, gender:"m", guessGender:true, category:"classroom"},
    {en:"a marker",                    fr:"un marqueur",          alts:["un marqueur"],          needsHyphen:false, needsAccent:false, gender:"m", guessGender:true, category:"classroom"},
    {en:"a board eraser",              fr:"une brosse",           alts:["une brosse"],           needsHyphen:false, needsAccent:false, gender:"f", guessGender:true, category:"classroom"},
    {en:"a tablet",                    fr:"une tablette",         alts:["une tablette"],         needsHyphen:false, needsAccent:false, gender:"f", guessGender:true, category:"classroom"},
    {en:"a (teacher's) desk",          fr:"un bureau",            alts:["un bureau"],            needsHyphen:false, needsAccent:false, gender:"m", guessGender:true, category:"classroom"},
    {en:"a classroom desk",            fr:"un pupitre",           alts:["un pupitre"],           needsHyphen:false, needsAccent:false, gender:"m", guessGender:true, category:"classroom"},
    {en:"a chair",                     fr:"une chaise",           alts:["une chaise"],           needsHyphen:false, needsAccent:false, gender:"f", guessGender:true, category:"classroom"},
    {en:"a window",                    fr:"une fenêtre",          alts:["une fenêtre"],          needsHyphen:false, needsAccent:true,  gender:"f", guessGender:true, category:"classroom"},
    {en:"a door",                      fr:"une porte",            alts:["une porte"],            needsHyphen:false, needsAccent:false, gender:"f", guessGender:true, category:"classroom"},
    {en:"a wall",                      fr:"un mur",               alts:["un mur"],               needsHyphen:false, needsAccent:false, gender:"m", guessGender:true, category:"classroom"},
    {en:"a clock",                     fr:"une horloge",          alts:["une horloge"],          needsHyphen:false, needsAccent:false, gender:"f", guessGender:true, category:"classroom"},
    {en:"a watch",                     fr:"une montre",           alts:["une montre"],           needsHyphen:false, needsAccent:false, gender:"f", guessGender:true, category:"classroom"},
    {en:"a computer",                  fr:"un ordinateur",        alts:["un ordinateur"],        needsHyphen:false, needsAccent:false, gender:"m", guessGender:true, category:"classroom"},
    {en:"a laptop",                    fr:"un ordinateur portable", alts:["un ordinateur portable"], needsHyphen:false, needsAccent:false, gender:"m", guessGender:true, category:"classroom"},
    {en:"a cellphone",                 fr:"un portable",          alts:["un portable"],          needsHyphen:false, needsAccent:false, gender:"m", guessGender:true, category:"classroom"},
    {en:"the ceiling",                 fr:"le plafond",           alts:["le plafond"],           needsHyphen:false, needsAccent:false, gender:"m", guessGender:true, category:"classroom"},
    {en:"the floor",                   fr:"le plancher",          alts:["le plancher"],          needsHyphen:false, needsAccent:false, gender:"m", guessGender:true, category:"classroom"},
    {en:"the lights",                  fr:"les lumières",         alts:["les lumières"],         needsHyphen:false, needsAccent:true,  gender:"f", guessGender:true, category:"classroom"},
    {en:"a name",                      fr:"un nom",               alts:["un nom"],               needsHyphen:false, needsAccent:false, gender:"m", guessGender:true, category:"classroom"},
  
    // ===== USEFUL EXPRESSIONS — Il y a + questions (B.1, B.2) =====
    {en:"There is/are a... (masc.)",   fr:"Il y a un...",         alts:["Il y a un...","Il y a un"], needsHyphen:false, needsAccent:false, gender:"m", category:"useful"},
    {en:"There is/are a... (fem.)",    fr:"Il y a une...",        alts:["Il y a une...","Il y a une"], needsHyphen:false, needsAccent:false, gender:"f", category:"useful"},
    {en:"There is/are some...",        fr:"Il y a des...",        alts:["Il y a des...","Il y a des"], needsHyphen:false, needsAccent:false, gender:"both", category:"useful"},
    {en:"There isn't a/any...",        fr:"Il n'y a pas de...",   alts:["Il n'y a pas de...","Il n'y a pas de"], needsHyphen:false, needsAccent:false, gender:"both", category:"useful"},
    {en:"There isn't a/any... (before vowel/mute h)", fr:"Il n'y a pas d'...", alts:["Il n'y a pas d'...","Il n'y a pas d'"], needsHyphen:false, needsAccent:false, gender:"both", category:"useful"},
    {en:"What is there in...?",        fr:"Qu'est-ce qu'il y a dans... ?", alts:["Qu'est-ce qu'il y a dans...","Qu'est-ce qu'il y a dans","Qu'est-ce qu'il y a dans ?"], needsHyphen:false, needsAccent:false, gender:"both", category:"useful"},
    {en:"What is there?",              fr:"Qu'est-ce qu'il y a ?", alts:["Qu'est-ce qu'il y a","Qu'est-ce qu'il y a ?","Qu'est-ce qu'il y a?"], needsHyphen:false, needsAccent:false, gender:"both", category:"useful"},
    {en:"on the table",                fr:"sur la table",         alts:["sur la table"],         needsHyphen:false, needsAccent:false, gender:"f", category:"useful"},
    {en:"in the classroom",            fr:"dans la salle de classe", alts:["dans la salle de classe"], needsHyphen:false, needsAccent:false, gender:"f", category:"useful"},
    {en:"the classroom",               fr:"la salle de classe",   alts:["la salle de classe"],   needsHyphen:false, needsAccent:false, gender:"f", category:"useful"},
  
    // ===== IDENTIFYING — Étape 2 (B.2) =====
    {en:"What is it/that? (open)",     fr:"Qu'est-ce que c'est ?", alts:["Qu'est-ce que c'est","Qu'est-ce que c'est ?","Qu'est-ce que c'est?"], needsHyphen:false, needsAccent:false, gender:"both", category:"identify"},
    {en:"It's a notebook.",            fr:"C'est un cahier.",     alts:["C'est un cahier","C'est un cahier."], needsHyphen:false, needsAccent:false, gender:"m", category:"identify"},
    {en:"It's a chair.",               fr:"C'est une chaise.",    alts:["C'est une chaise","C'est une chaise."], needsHyphen:false, needsAccent:false, gender:"f", category:"identify"},
    {en:"It's a pen.",                 fr:"C'est un stylo.",      alts:["C'est un stylo","C'est un stylo."], needsHyphen:false, needsAccent:false, gender:"m", category:"identify"},
    {en:"It's not a notebook.",        fr:"Ce n'est pas un cahier.", alts:["Ce n'est pas un cahier","Ce n'est pas un cahier."], needsHyphen:false, needsAccent:false, gender:"m", category:"identify"},
    {en:"It's not a... (masc.)",       fr:"Ce n'est pas un...",   alts:["Ce n'est pas un...","Ce n'est pas un"], needsHyphen:false, needsAccent:false, gender:"m", category:"identify"},
    {en:"It's not a... (fem.)",        fr:"Ce n'est pas une...",  alts:["Ce n'est pas une...","Ce n'est pas une"], needsHyphen:false, needsAccent:false, gender:"f", category:"identify"},
  
 
  
    // ===== ALPHABET — Accent names =====
    {en:"acute accent (é)",            fr:"accent aigu",          alts:["accent aigu"],          needsHyphen:false, needsAccent:false, gender:"both", category:"alphabet"},
    {en:"grave accent (è, à)",         fr:"accent grave",         alts:["accent grave"],         needsHyphen:false, needsAccent:false, gender:"both", category:"alphabet"},
    {en:"circumflex accent (ê, â, î, ô, û)", fr:"accent circonflexe", alts:["accent circonflexe"], needsHyphen:false, needsAccent:false, gender:"both", category:"alphabet"},
    {en:"diaeresis / umlaut (ë, ï)",   fr:"tréma",                alts:["tréma"],                needsHyphen:false, needsAccent:true,  gender:"both", category:"alphabet"},
    {en:"cedilla (ç)",                 fr:"cédille",              alts:["cédille"],              needsHyphen:false, needsAccent:true,  gender:"both", category:"alphabet"},
  
    // ===== CALENDAR — Days of the week (Page 24, 32) =====
    {en:"Monday",                      fr:"lundi",                alts:["lundi"],                needsHyphen:false, needsAccent:false, gender:"both", category:"calendar"},
    {en:"Tuesday",                     fr:"mardi",                alts:["mardi"],                needsHyphen:false, needsAccent:false, gender:"both", category:"calendar"},
    {en:"Wednesday",                   fr:"mercredi",             alts:["mercredi"],             needsHyphen:false, needsAccent:false, gender:"both", category:"calendar"},
    {en:"Thursday",                    fr:"jeudi",                alts:["jeudi"],                needsHyphen:false, needsAccent:false, gender:"both", category:"calendar"},
    {en:"Friday",                      fr:"vendredi",             alts:["vendredi"],             needsHyphen:false, needsAccent:false, gender:"both", category:"calendar"},
    {en:"Saturday",                    fr:"samedi",               alts:["samedi"],               needsHyphen:false, needsAccent:false, gender:"both", category:"calendar"},
    {en:"Sunday",                      fr:"dimanche",             alts:["dimanche"],             needsHyphen:false, needsAccent:false, gender:"both", category:"calendar"},
    {en:"the days of the week",        fr:"les jours de la semaine", alts:["les jours de la semaine"], needsHyphen:false, needsAccent:false, gender:"m", category:"calendar"},
    {en:"a day",                       fr:"un jour",              alts:["un jour"],              needsHyphen:false, needsAccent:false, gender:"m", category:"calendar"},
    {en:"every day",                   fr:"tous les jours",       alts:["tous les jours"],       needsHyphen:false, needsAccent:false, gender:"both", category:"calendar"},
    {en:"a week",                      fr:"une semaine",          alts:["une semaine"],          needsHyphen:false, needsAccent:false, gender:"f", category:"calendar"},
  
    // ===== CALENDAR — Months of the year =====
    {en:"January",                     fr:"janvier",              alts:["janvier"],              needsHyphen:false, needsAccent:false, gender:"both", category:"calendar"},
    {en:"February",                    fr:"février",              alts:["février"],              needsHyphen:false, needsAccent:true,  gender:"both", category:"calendar"},
    {en:"March",                       fr:"mars",                 alts:["mars"],                 needsHyphen:false, needsAccent:false, gender:"both", category:"calendar"},
    {en:"April",                       fr:"avril",                alts:["avril"],                needsHyphen:false, needsAccent:false, gender:"both", category:"calendar"},
    {en:"May",                         fr:"mai",                  alts:["mai"],                  needsHyphen:false, needsAccent:false, gender:"both", category:"calendar"},
    {en:"June",                        fr:"juin",                 alts:["juin"],                 needsHyphen:false, needsAccent:false, gender:"both", category:"calendar"},
    {en:"July",                        fr:"juillet",              alts:["juillet"],              needsHyphen:false, needsAccent:false, gender:"both", category:"calendar"},
    {en:"August",                      fr:"août",                 alts:["août","aout"],          needsHyphen:false, needsAccent:true,  gender:"both", category:"calendar"},
    {en:"September",                   fr:"septembre",            alts:["septembre"],            needsHyphen:false, needsAccent:false, gender:"both", category:"calendar"},
    {en:"October",                     fr:"octobre",              alts:["octobre"],              needsHyphen:false, needsAccent:false, gender:"both", category:"calendar"},
    {en:"November",                    fr:"novembre",             alts:["novembre"],             needsHyphen:false, needsAccent:false, gender:"both", category:"calendar"},
    {en:"December",                    fr:"décembre",             alts:["décembre"],             needsHyphen:false, needsAccent:true,  gender:"both", category:"calendar"},
    {en:"the months of the year",      fr:"les mois de l'année",  alts:["les mois de l'année"],  needsHyphen:false, needsAccent:true,  gender:"m", category:"calendar"},
    {en:"a month",                     fr:"un mois",              alts:["un mois"],              needsHyphen:false, needsAccent:false, gender:"m", category:"calendar"},
    {en:"a year",                      fr:"une année",            alts:["une année"],            needsHyphen:false, needsAccent:true,  gender:"f", category:"calendar"},
    {en:"What's the date today?",      fr:"Quelle est la date aujourd'hui ?", alts:["Quelle est la date aujourd'hui","Quelle est la date aujourd'hui ?","Quelle est la date aujourd'hui?"], needsHyphen:false, needsAccent:false, gender:"both", category:"calendar"},
    {en:"What's the date of your birthday?", fr:"Quelle est la date de ton anniversaire ?", alts:["Quelle est la date de ton anniversaire","Quelle est la date de ton anniversaire ?","Quelle est la date de ton anniversaire?"], needsHyphen:false, needsAccent:false, gender:"both", category:"calendar"},
    {en:"a birthday",                  fr:"un anniversaire",      alts:["un anniversaire"],      needsHyphen:false, needsAccent:false, gender:"m", category:"calendar"},
    {en:"Happy birthday!",             fr:"Joyeux anniversaire !", alts:["Joyeux anniversaire","Joyeux anniversaire !","Joyeux anniversaire!"], needsHyphen:false, needsAccent:false, gender:"both", category:"calendar"},
    {en:"It's the first of May.",      fr:"C'est le premier mai.", alts:["C'est le premier mai","C'est le premier mai."], needsHyphen:false, needsAccent:false, gender:"both", category:"calendar"},
    {en:"the first (of the month)",    fr:"le premier",           alts:["le premier"],           needsHyphen:false, needsAccent:false, gender:"m", category:"calendar"},
    {en:"vacation / holidays",         fr:"les vacances",         alts:["les vacances"],         needsHyphen:false, needsAccent:false, gender:"f", category:"calendar"},
    {en:"Christmas",                   fr:"Noël",                 alts:["Noël"],                 needsHyphen:false, needsAccent:true,  gender:"both", category:"calendar"},
  
    // ===== NUMBERS 40-100 (Page 25) =====
    {en:"forty (40)",                  fr:"quarante",             alts:["quarante"],             needsHyphen:false, needsAccent:false, gender:"both", category:"numbers"},
    {en:"forty-one (41)",              fr:"quarante et un",       alts:["quarante et un"],       needsHyphen:false, needsAccent:false, gender:"both", category:"numbers"},
    {en:"forty-two (42)",              fr:"quarante-deux",        alts:["quarante-deux"],        needsHyphen:true,  needsAccent:false, gender:"both", category:"numbers"},
    {en:"forty-three (43)",            fr:"quarante-trois",       alts:["quarante-trois"],       needsHyphen:true,  needsAccent:false, gender:"both", category:"numbers"},
    {en:"forty-four (44)",             fr:"quarante-quatre",      alts:["quarante-quatre"],      needsHyphen:true,  needsAccent:false, gender:"both", category:"numbers"},
    {en:"forty-five (45)",             fr:"quarante-cinq",        alts:["quarante-cinq"],        needsHyphen:true,  needsAccent:false, gender:"both", category:"numbers"},
    {en:"forty-six (46)",              fr:"quarante-six",         alts:["quarante-six"],         needsHyphen:true,  needsAccent:false, gender:"both", category:"numbers"},
    {en:"forty-seven (47)",            fr:"quarante-sept",        alts:["quarante-sept"],        needsHyphen:true,  needsAccent:false, gender:"both", category:"numbers"},
    {en:"forty-eight (48)",            fr:"quarante-huit",        alts:["quarante-huit"],        needsHyphen:true,  needsAccent:false, gender:"both", category:"numbers"},
    {en:"forty-nine (49)",             fr:"quarante-neuf",        alts:["quarante-neuf"],        needsHyphen:true,  needsAccent:false, gender:"both", category:"numbers"},
    {en:"fifty (50)",                  fr:"cinquante",            alts:["cinquante"],            needsHyphen:false, needsAccent:false, gender:"both", category:"numbers"},
    {en:"fifty-one (51)",              fr:"cinquante et un",      alts:["cinquante et un"],      needsHyphen:false, needsAccent:false, gender:"both", category:"numbers"},
    {en:"fifty-two (52)",              fr:"cinquante-deux",       alts:["cinquante-deux"],       needsHyphen:true,  needsAccent:false, gender:"both", category:"numbers"},
    {en:"fifty-three (53)",            fr:"cinquante-trois",      alts:["cinquante-trois"],      needsHyphen:true,  needsAccent:false, gender:"both", category:"numbers"},
    {en:"fifty-four (54)",             fr:"cinquante-quatre",     alts:["cinquante-quatre"],     needsHyphen:true,  needsAccent:false, gender:"both", category:"numbers"},
    {en:"fifty-five (55)",             fr:"cinquante-cinq",       alts:["cinquante-cinq"],       needsHyphen:true,  needsAccent:false, gender:"both", category:"numbers"},
    {en:"fifty-six (56)",              fr:"cinquante-six",        alts:["cinquante-six"],        needsHyphen:true,  needsAccent:false, gender:"both", category:"numbers"},
    {en:"fifty-seven (57)",            fr:"cinquante-sept",       alts:["cinquante-sept"],       needsHyphen:true,  needsAccent:false, gender:"both", category:"numbers"},
    {en:"fifty-eight (58)",            fr:"cinquante-huit",       alts:["cinquante-huit"],       needsHyphen:true,  needsAccent:false, gender:"both", category:"numbers"},
    {en:"fifty-nine (59)",             fr:"cinquante-neuf",       alts:["cinquante-neuf"],       needsHyphen:true,  needsAccent:false, gender:"both", category:"numbers"},
    {en:"sixty (60)",                  fr:"soixante",             alts:["soixante"],             needsHyphen:false, needsAccent:false, gender:"both", category:"numbers"},
    {en:"sixty-one (61)",              fr:"soixante et un",       alts:["soixante et un"],       needsHyphen:false, needsAccent:false, gender:"both", category:"numbers"},
    {en:"sixty-two (62)",              fr:"soixante-deux",        alts:["soixante-deux"],        needsHyphen:true,  needsAccent:false, gender:"both", category:"numbers"},
    {en:"sixty-three (63)",            fr:"soixante-trois",       alts:["soixante-trois"],       needsHyphen:true,  needsAccent:false, gender:"both", category:"numbers"},
    {en:"sixty-four (64)",             fr:"soixante-quatre",      alts:["soixante-quatre"],      needsHyphen:true,  needsAccent:false, gender:"both", category:"numbers"},
    {en:"sixty-five (65)",             fr:"soixante-cinq",        alts:["soixante-cinq"],        needsHyphen:true,  needsAccent:false, gender:"both", category:"numbers"},
    {en:"sixty-six (66)",              fr:"soixante-six",         alts:["soixante-six"],         needsHyphen:true,  needsAccent:false, gender:"both", category:"numbers"},
    {en:"sixty-seven (67)",            fr:"soixante-sept",        alts:["soixante-sept"],        needsHyphen:true,  needsAccent:false, gender:"both", category:"numbers"},
    {en:"sixty-eight (68)",            fr:"soixante-huit",        alts:["soixante-huit"],        needsHyphen:true,  needsAccent:false, gender:"both", category:"numbers"},
    {en:"sixty-nine (69)",             fr:"soixante-neuf",        alts:["soixante-neuf"],        needsHyphen:true,  needsAccent:false, gender:"both", category:"numbers"},
    {en:"seventy (70)",                fr:"soixante-dix",         alts:["soixante-dix"],         needsHyphen:true,  needsAccent:false, gender:"both", category:"numbers"},
    {en:"seventy-one (71)",            fr:"soixante et onze",     alts:["soixante et onze"],     needsHyphen:false, needsAccent:false, gender:"both", category:"numbers"},
    {en:"seventy-two (72)",            fr:"soixante-douze",       alts:["soixante-douze"],       needsHyphen:true,  needsAccent:false, gender:"both", category:"numbers"},
    {en:"seventy-three (73)",          fr:"soixante-treize",      alts:["soixante-treize"],      needsHyphen:true,  needsAccent:false, gender:"both", category:"numbers"},
    {en:"seventy-four (74)",           fr:"soixante-quatorze",    alts:["soixante-quatorze"],    needsHyphen:true,  needsAccent:false, gender:"both", category:"numbers"},
    {en:"seventy-five (75)",           fr:"soixante-quinze",      alts:["soixante-quinze"],      needsHyphen:true,  needsAccent:false, gender:"both", category:"numbers"},
    {en:"seventy-six (76)",            fr:"soixante-seize",       alts:["soixante-seize"],       needsHyphen:true,  needsAccent:false, gender:"both", category:"numbers"},
    {en:"seventy-seven (77)",          fr:"soixante-dix-sept",    alts:["soixante-dix-sept"],    needsHyphen:true,  needsAccent:false, gender:"both", category:"numbers"},
    {en:"seventy-eight (78)",          fr:"soixante-dix-huit",    alts:["soixante-dix-huit"],    needsHyphen:true,  needsAccent:false, gender:"both", category:"numbers"},
    {en:"seventy-nine (79)",           fr:"soixante-dix-neuf",    alts:["soixante-dix-neuf"],    needsHyphen:true,  needsAccent:false, gender:"both", category:"numbers"},
    {en:"eighty (80)",                 fr:"quatre-vingts",        alts:["quatre-vingts"],        needsHyphen:true,  needsAccent:false, gender:"both", category:"numbers"},
    {en:"eighty-one (81)",             fr:"quatre-vingt-un",      alts:["quatre-vingt-un"],      needsHyphen:true,  needsAccent:false, gender:"both", category:"numbers"},
    {en:"eighty-two (82)",             fr:"quatre-vingt-deux",    alts:["quatre-vingt-deux"],    needsHyphen:true,  needsAccent:false, gender:"both", category:"numbers"},
    {en:"eighty-three (83)",           fr:"quatre-vingt-trois",   alts:["quatre-vingt-trois"],   needsHyphen:true,  needsAccent:false, gender:"both", category:"numbers"},
    {en:"eighty-four (84)",            fr:"quatre-vingt-quatre",  alts:["quatre-vingt-quatre"],  needsHyphen:true,  needsAccent:false, gender:"both", category:"numbers"},
    {en:"eighty-five (85)",            fr:"quatre-vingt-cinq",    alts:["quatre-vingt-cinq"],    needsHyphen:true,  needsAccent:false, gender:"both", category:"numbers"},
    {en:"eighty-six (86)",             fr:"quatre-vingt-six",     alts:["quatre-vingt-six"],     needsHyphen:true,  needsAccent:false, gender:"both", category:"numbers"},
    {en:"eighty-seven (87)",           fr:"quatre-vingt-sept",    alts:["quatre-vingt-sept"],    needsHyphen:true,  needsAccent:false, gender:"both", category:"numbers"},
    {en:"eighty-eight (88)",           fr:"quatre-vingt-huit",    alts:["quatre-vingt-huit"],    needsHyphen:true,  needsAccent:false, gender:"both", category:"numbers"},
    {en:"eighty-nine (89)",            fr:"quatre-vingt-neuf",    alts:["quatre-vingt-neuf"],    needsHyphen:true,  needsAccent:false, gender:"both", category:"numbers"},
    {en:"ninety (90)",                 fr:"quatre-vingt-dix",     alts:["quatre-vingt-dix"],     needsHyphen:true,  needsAccent:false, gender:"both", category:"numbers"},
    {en:"ninety-one (91)",             fr:"quatre-vingt-onze",    alts:["quatre-vingt-onze"],    needsHyphen:true,  needsAccent:false, gender:"both", category:"numbers"},
    {en:"ninety-two (92)",             fr:"quatre-vingt-douze",   alts:["quatre-vingt-douze"],   needsHyphen:true,  needsAccent:false, gender:"both", category:"numbers"},
    {en:"ninety-three (93)",           fr:"quatre-vingt-treize",  alts:["quatre-vingt-treize"],  needsHyphen:true,  needsAccent:false, gender:"both", category:"numbers"},
    {en:"ninety-four (94)",            fr:"quatre-vingt-quatorze",alts:["quatre-vingt-quatorze"],needsHyphen:true,  needsAccent:false, gender:"both", category:"numbers"},
    {en:"ninety-five (95)",            fr:"quatre-vingt-quinze",  alts:["quatre-vingt-quinze"],  needsHyphen:true,  needsAccent:false, gender:"both", category:"numbers"},
    {en:"ninety-six (96)",             fr:"quatre-vingt-seize",   alts:["quatre-vingt-seize"],   needsHyphen:true,  needsAccent:false, gender:"both", category:"numbers"},
    {en:"ninety-seven (97)",           fr:"quatre-vingt-dix-sept",alts:["quatre-vingt-dix-sept"],needsHyphen:true,  needsAccent:false, gender:"both", category:"numbers"},
    {en:"ninety-eight (98)",           fr:"quatre-vingt-dix-huit",alts:["quatre-vingt-dix-huit"],needsHyphen:true,  needsAccent:false, gender:"both", category:"numbers"},
    {en:"ninety-nine (99)",            fr:"quatre-vingt-dix-neuf",alts:["quatre-vingt-dix-neuf"],needsHyphen:true,  needsAccent:false, gender:"both", category:"numbers"},
    {en:"one hundred (100)",           fr:"cent",                 alts:["cent"],                 needsHyphen:false, needsAccent:false, gender:"both", category:"numbers"},
  
    // ===== TIME — L'heure (B.4, Page 25, 32) =====
    {en:"What time is it?",            fr:"Quelle heure est-il ?", alts:["Quelle heure est-il","Quelle heure est-il ?","Quelle heure est-il?"], needsHyphen:true, needsAccent:false, gender:"both", category:"time"},
    {en:"At what time...?",            fr:"À quelle heure... ?",  alts:["À quelle heure...","À quelle heure","À quelle heure ?","À quelle heure?"], needsHyphen:false, needsAccent:true,  gender:"both", category:"time"},
    {en:"It is... o'clock.",           fr:"Il est... heure(s).",  alts:["Il est... heure(s)","Il est... heures","Il est... heure"], needsHyphen:false, needsAccent:false, gender:"both", category:"time"},
    {en:"It is one o'clock.",          fr:"Il est une heure.",    alts:["Il est une heure","Il est une heure."], needsHyphen:false, needsAccent:false, gender:"both", category:"time"},
    {en:"It is two o'clock.",          fr:"Il est deux heures.",  alts:["Il est deux heures","Il est deux heures."], needsHyphen:false, needsAccent:false, gender:"both", category:"time"},
    {en:"It is nine o'clock.",         fr:"Il est neuf heures.",  alts:["Il est neuf heures","Il est neuf heures."], needsHyphen:false, needsAccent:false, gender:"both", category:"time"},
    {en:"It is noon.",                 fr:"Il est midi.",         alts:["Il est midi","Il est midi."], needsHyphen:false, needsAccent:false, gender:"both", category:"time"},
    {en:"It is midnight.",             fr:"Il est minuit.",       alts:["Il est minuit","Il est minuit."], needsHyphen:false, needsAccent:false, gender:"both", category:"time"},
    {en:"noon",                        fr:"midi",                 alts:["midi"],                 needsHyphen:false, needsAccent:false, gender:"m", category:"time"},
    {en:"midnight",                    fr:"minuit",               alts:["minuit"],               needsHyphen:false, needsAccent:false, gender:"m", category:"time"},
    {en:"It is half past noon.",       fr:"Il est midi et demi.", alts:["Il est midi et demi","Il est midi et demi."], needsHyphen:false, needsAccent:false, gender:"both", category:"time"},
    {en:"It is half past midnight.",   fr:"Il est minuit et demi.", alts:["Il est minuit et demi","Il est minuit et demi."], needsHyphen:false, needsAccent:false, gender:"both", category:"time"},
    {en:"It is half past one.",        fr:"Il est une heure et demie.", alts:["Il est une heure et demie","Il est une heure et demie."], needsHyphen:false, needsAccent:false, gender:"both", category:"time"},
    {en:"It is half past nine.",       fr:"Il est neuf heures et demie.", alts:["Il est neuf heures et demie","Il est neuf heures et demie."], needsHyphen:false, needsAccent:false, gender:"both", category:"time"},
    {en:"It is a quarter past one.",   fr:"Il est une heure et quart.", alts:["Il est une heure et quart","Il est une heure et quart."], needsHyphen:false, needsAccent:false, gender:"both", category:"time"},
    {en:"It is a quarter past midnight.", fr:"Il est minuit et quart.", alts:["Il est minuit et quart","Il est minuit et quart."], needsHyphen:false, needsAccent:false, gender:"both", category:"time"},
    {en:"It is a quarter to four.",    fr:"Il est quatre heures moins le quart.", alts:["Il est quatre heures moins le quart","Il est quatre heures moins le quart."], needsHyphen:false, needsAccent:false, gender:"both", category:"time"},
    {en:"It is a quarter to eight.",   fr:"Il est huit heures moins le quart.", alts:["Il est huit heures moins le quart","Il est huit heures moins le quart."], needsHyphen:false, needsAccent:false, gender:"both", category:"time"},
    {en:"It is five to two.",          fr:"Il est deux heures moins cinq.", alts:["Il est deux heures moins cinq","Il est deux heures moins cinq."], needsHyphen:false, needsAccent:false, gender:"both", category:"time"},
    {en:"It is twenty to eleven.",     fr:"Il est onze heures moins vingt.", alts:["Il est onze heures moins vingt","Il est onze heures moins vingt."], needsHyphen:false, needsAccent:false, gender:"both", category:"time"},
    {en:"It is ten past ten.",         fr:"Il est dix heures dix.", alts:["Il est dix heures dix","Il est dix heures dix."], needsHyphen:false, needsAccent:false, gender:"both", category:"time"},
    {en:"It is twenty-five past ten.", fr:"Il est dix heures vingt-cinq.", alts:["Il est dix heures vingt-cinq","Il est dix heures vingt-cinq."], needsHyphen:true, needsAccent:false, gender:"both", category:"time"},
    {en:"...thirty (half past)",       fr:"...et demi(e)",        alts:["et demi","et demie","et demi(e)"], needsHyphen:false, needsAccent:false, gender:"both", category:"time"},
    {en:"...fifteen (a quarter past)", fr:"...et quart",          alts:["et quart","...et quart"], needsHyphen:false, needsAccent:false, gender:"both", category:"time"},
    {en:"...a quarter to",             fr:"...moins le quart",    alts:["moins le quart","...moins le quart"], needsHyphen:false, needsAccent:false, gender:"both", category:"time"},
    {en:"...in the morning (A.M.)",    fr:"...du matin",          alts:["du matin","...du matin"], needsHyphen:false, needsAccent:false, gender:"both", category:"time"},
    {en:"...in the afternoon (P.M.)",  fr:"...de l'après-midi",   alts:["de l'après-midi","...de l'après-midi"], needsHyphen:false, needsAccent:true,  gender:"both", category:"time"},
    {en:"...in the evening (P.M.)",    fr:"...du soir",           alts:["du soir","...du soir"], needsHyphen:false, needsAccent:false, gender:"both", category:"time"},
    {en:"the morning",                 fr:"le matin",             alts:["le matin"],             needsHyphen:false, needsAccent:false, gender:"m", category:"time"},
    {en:"the afternoon",               fr:"l'après-midi",         alts:["l'après-midi"],         needsHyphen:false, needsAccent:true,  gender:"m", category:"time"},
    {en:"the evening",                 fr:"le soir",              alts:["le soir"],              needsHyphen:false, needsAccent:false, gender:"m", category:"time"},
    {en:"an hour",                     fr:"une heure",            alts:["une heure"],            needsHyphen:false, needsAccent:false, gender:"f", category:"time"},
    {en:"a minute",                    fr:"une minute",           alts:["une minute"],           needsHyphen:false, needsAccent:false, gender:"f", category:"time"},
    {en:"a second",                    fr:"une seconde",          alts:["une seconde"],          needsHyphen:false, needsAccent:false, gender:"f", category:"time"},
    {en:"What time does... begin?",    fr:"À quelle heure commence... ?", alts:["À quelle heure commence...","À quelle heure commence","À quelle heure commence ?"], needsHyphen:false, needsAccent:true, gender:"both", category:"time"},
    {en:"It begins at... (masc./fem.)", fr:"Il/Elle commence à...", alts:["Il commence à...","Elle commence à...","Il commence à","Elle commence à"], needsHyphen:false, needsAccent:true, gender:"both", category:"time"},
  // ===== TELLING TIME — translation practice =====
  {en:"It is 10:45.",            fr:"Il est onze heures moins le quart.",       alts:["Il est onze heures moins le quart","Il est onze heures moins le quart.","Il est dix heures quarante-cinq","Il est dix heures quarante-cinq."],                       needsHyphen:false, needsAccent:false, gender:"both", category:"time"},
  {en:"It is 11:45.",            fr:"Il est midi moins le quart.",              alts:["Il est midi moins le quart","Il est midi moins le quart.","Il est onze heures quarante-cinq","Il est onze heures quarante-cinq."],                                     needsHyphen:false, needsAccent:false, gender:"both", category:"time"},
  {en:"It is 13:45.",            fr:"Il est treize heures quarante-cinq.",      alts:["Il est treize heures quarante-cinq","Il est treize heures quarante-cinq."],                                                                                          needsHyphen:true,  needsAccent:false, gender:"both", category:"time"},
  {en:"It is 22:10.",            fr:"Il est vingt-deux heures dix.",            alts:["Il est vingt-deux heures dix","Il est vingt-deux heures dix."],                                                                                                      needsHyphen:true,  needsAccent:false, gender:"both", category:"time"},
  {en:"It is 7:15 AM.",          fr:"Il est sept heures et quart.",             alts:["Il est sept heures et quart","Il est sept heures et quart.","Il est sept heures quinze","Il est sept heures quinze."],                                              needsHyphen:false, needsAccent:false, gender:"both", category:"time"},
  {en:"It is 7:15 PM.",          fr:"Il est dix-neuf heures quinze.",           alts:["Il est dix-neuf heures quinze","Il est dix-neuf heures quinze."],                                                                                                    needsHyphen:true,  needsAccent:false, gender:"both", category:"time"},
  {en:"It is 8:30 AM.",          fr:"Il est huit heures et demie.",             alts:["Il est huit heures et demie","Il est huit heures et demie.","Il est huit heures trente","Il est huit heures trente."],                                              needsHyphen:false, needsAccent:false, gender:"both", category:"time"},
  {en:"It is 8:30 PM.",          fr:"Il est vingt heures trente.",              alts:["Il est vingt heures trente","Il est vingt heures trente."],                                                                                                          needsHyphen:false, needsAccent:false, gender:"both", category:"time"},
  {en:"It is 12:00 PM (noon).",  fr:"Il est midi.",                             alts:["Il est midi","Il est midi."],                                                                                                                                        needsHyphen:false, needsAccent:false, gender:"both", category:"time"},
  {en:"It is 12:00 AM (midnight).", fr:"Il est minuit.",                        alts:["Il est minuit","Il est minuit."],                                                                                                                                    needsHyphen:false, needsAccent:false, gender:"both", category:"time"},
  {en:"It is 12:30 PM (half past noon).", fr:"Il est midi et demi.",            alts:["Il est midi et demi","Il est midi et demi."],                                                                                                                        needsHyphen:false, needsAccent:false, gender:"both", category:"time"},
  {en:"It is 1:00 AM.",          fr:"Il est une heure.",                        alts:["Il est une heure","Il est une heure."],                                                                                                                              needsHyphen:false, needsAccent:false, gender:"both", category:"time"},
  {en:"It is 3:20 PM.",          fr:"Il est quinze heures vingt.",              alts:["Il est quinze heures vingt","Il est quinze heures vingt.","Il est trois heures vingt","Il est trois heures vingt."],                                                needsHyphen:false, needsAccent:false, gender:"both", category:"time"},
  {en:"It is 5:50 PM.",          fr:"Il est six heures moins dix.",             alts:["Il est six heures moins dix","Il est six heures moins dix.","Il est dix-sept heures cinquante","Il est dix-sept heures cinquante."],                                needsHyphen:false, needsAccent:false, gender:"both", category:"time"},
  {en:"It is 9:05 AM.",          fr:"Il est neuf heures cinq.",                 alts:["Il est neuf heures cinq","Il est neuf heures cinq."],                                                                                                                needsHyphen:false, needsAccent:false, gender:"both", category:"time"},
    // ===== SCHOOL SUBJECTS — Les cours (Page 27, 32-33) =====
    {en:"a class / course",            fr:"un cours",             alts:["un cours"],             needsHyphen:false, needsAccent:false, gender:"m", guessGender:true, category:"subjects"},
    {en:"performing arts",             fr:"les arts du spectacle",alts:["les arts du spectacle"],needsHyphen:false, needsAccent:false, gender:"m", category:"subjects"},
    {en:"fine arts",                   fr:"les beaux-arts",       alts:["les beaux-arts"],       needsHyphen:true,  needsAccent:false, gender:"m", category:"subjects"},
    {en:"biology",                     fr:"la biologie",          alts:["la biologie"],          needsHyphen:false, needsAccent:false, gender:"f", category:"subjects"},
    {en:"chemistry",                   fr:"la chimie",            alts:["la chimie"],            needsHyphen:false, needsAccent:false, gender:"f", category:"subjects"},
    {en:"accounting",                  fr:"la comptabilité",      alts:["la comptabilité"],      needsHyphen:false, needsAccent:true,  gender:"f", category:"subjects"},
    {en:"graphic arts / drawing",      fr:"le dessin",            alts:["le dessin"],            needsHyphen:false, needsAccent:false, gender:"m", category:"subjects"},
    {en:"economics",                   fr:"l'économie",           alts:["l'économie"],           needsHyphen:false, needsAccent:true,  gender:"f", category:"subjects"},
    {en:"French (the subject)",        fr:"le français",          alts:["le français"],          needsHyphen:false, needsAccent:true,  gender:"m", category:"subjects"},
    {en:"civil engineering",           fr:"le génie civil",       alts:["le génie civil"],       needsHyphen:false, needsAccent:true,  gender:"m", category:"subjects"},
    {en:"geography",                   fr:"la géographie",        alts:["la géographie"],        needsHyphen:false, needsAccent:true,  gender:"f", category:"subjects"},
    {en:"geology",                     fr:"la géologie",          alts:["la géologie"],          needsHyphen:false, needsAccent:true,  gender:"f", category:"subjects"},
    {en:"gymnastics / phys. ed.",      fr:"la gymnastique",       alts:["la gymnastique"],       needsHyphen:false, needsAccent:false, gender:"f", category:"subjects"},
    {en:"history",                     fr:"l'histoire",           alts:["l'histoire"],           needsHyphen:false, needsAccent:false, gender:"f", category:"subjects"},
    {en:"art history",                 fr:"l'histoire de l'art",  alts:["l'histoire de l'art"],  needsHyphen:false, needsAccent:false, gender:"f", category:"subjects"},
    {en:"computer science",            fr:"l'informatique",       alts:["l'informatique"],       needsHyphen:false, needsAccent:false, gender:"f", category:"subjects"},
    {en:"literature",                  fr:"la littérature",       alts:["la littérature"],       needsHyphen:false, needsAccent:true,  gender:"f", category:"subjects"},
    {en:"marketing",                   fr:"le marketing",         alts:["le marketing"],         needsHyphen:false, needsAccent:false, gender:"m", category:"subjects"},
    {en:"mathematics",                 fr:"les mathématiques",    alts:["les mathématiques","les maths"], needsHyphen:false, needsAccent:true, gender:"f", category:"subjects"},
    {en:"music",                       fr:"la musique",           alts:["la musique"],           needsHyphen:false, needsAccent:false, gender:"f", category:"subjects"},
    {en:"(oriental) philosophy",       fr:"la philosophie (orientale)", alts:["la philosophie","la philosophie orientale","la philosophie (orientale)"], needsHyphen:false, needsAccent:false, gender:"f", category:"subjects"},
    {en:"physics",                     fr:"la physique",          alts:["la physique"],          needsHyphen:false, needsAccent:false, gender:"f", category:"subjects"},
    {en:"psychology",                  fr:"la psychologie",       alts:["la psychologie"],       needsHyphen:false, needsAccent:false, gender:"f", category:"subjects"},
    {en:"advertising",                 fr:"la publicité",         alts:["la publicité"],         needsHyphen:false, needsAccent:true,  gender:"f", category:"subjects"},
    {en:"the sciences",                fr:"les sciences",         alts:["les sciences"],         needsHyphen:false, needsAccent:false, gender:"f", category:"subjects"},
    {en:"sociology",                   fr:"la sociologie",        alts:["la sociologie"],        needsHyphen:false, needsAccent:false, gender:"f", category:"subjects"},
    {en:"theatre / drama",             fr:"le théâtre",           alts:["le théâtre"],           needsHyphen:false, needsAccent:true,  gender:"m", category:"subjects"},
    {en:"Do you have a... class?",     fr:"Est-ce que tu as un cours de... ?", alts:["Est-ce que tu as un cours de...","Est-ce que tu as un cours de","Est-ce que tu as un cours de ?"], needsHyphen:false, needsAccent:false, gender:"both", category:"subjects"},
    {en:"Yes, I have a... class.",     fr:"Oui, j'ai un cours de...", alts:["Oui, j'ai un cours de...","Oui, j'ai un cours de"], needsHyphen:false, needsAccent:false, gender:"both", category:"subjects"},
    {en:"No, I don't have a... class.", fr:"Non, je n'ai pas de cours de...", alts:["Non, je n'ai pas de cours de...","Non, je n'ai pas de cours de"], needsHyphen:false, needsAccent:false, gender:"both", category:"subjects"},
  
    // ===== COURSE DESCRIPTORS (Page 33) =====
    {en:"boring",                      fr:"ennuyeux",             alts:["ennuyeux"],             needsHyphen:false, needsAccent:false, gender:"m", category:"subjects"},
    {en:"boring (fem.)",               fr:"ennuyeuse",            alts:["ennuyeuse"],            needsHyphen:false, needsAccent:false, gender:"f", category:"subjects"},
    {en:"easy",                        fr:"facile",               alts:["facile"],               needsHyphen:false, needsAccent:false, gender:"both", category:"subjects"},
    {en:"useless",                     fr:"inutile",              alts:["inutile"],              needsHyphen:false, needsAccent:false, gender:"both", category:"subjects"},
    {en:"exciting",                    fr:"passionnant",          alts:["passionnant"],          needsHyphen:false, needsAccent:false, gender:"m", category:"subjects"},
    {en:"exciting (fem.)",             fr:"passionnante",         alts:["passionnante"],         needsHyphen:false, needsAccent:false, gender:"f", category:"subjects"},
    {en:"useful",                      fr:"utile",                alts:["utile"],                needsHyphen:false, needsAccent:false, gender:"both", category:"subjects"},
    {en:"abstract",                    fr:"abstrait",             alts:["abstrait"],             needsHyphen:false, needsAccent:false, gender:"m", category:"subjects"},
    {en:"abstract (fem.)",             fr:"abstraite",            alts:["abstraite"],            needsHyphen:false, needsAccent:false, gender:"f", category:"subjects"},
    {en:"complicated",                 fr:"compliqué",            alts:["compliqué"],            needsHyphen:false, needsAccent:true,  gender:"m", category:"subjects"},
    {en:"complicated (fem.)",          fr:"compliquée",           alts:["compliquée"],           needsHyphen:false, needsAccent:true,  gender:"f", category:"subjects"},
    {en:"difficult",                   fr:"difficile",            alts:["difficile"],            needsHyphen:false, needsAccent:false, gender:"both", category:"subjects"},
    {en:"important",                   fr:"important",            alts:["important"],            needsHyphen:false, needsAccent:false, gender:"m", category:"subjects"},
    {en:"important (fem.)",            fr:"importante",           alts:["importante"],           needsHyphen:false, needsAccent:false, gender:"f", category:"subjects"},
    {en:"interesting",                 fr:"intéressant",          alts:["intéressant"],          needsHyphen:false, needsAccent:true,  gender:"m", category:"subjects"},
    {en:"interesting (fem.)",          fr:"intéressante",         alts:["intéressante"],         needsHyphen:false, needsAccent:true,  gender:"f", category:"subjects"},
    {en:"practical",                   fr:"pratique",             alts:["pratique"],             needsHyphen:false, needsAccent:false, gender:"both", category:"subjects"},
    {en:"superfluous / unnecessary",   fr:"superflu",             alts:["superflu"],             needsHyphen:false, needsAccent:false, gender:"m", category:"subjects"},
    {en:"superfluous (fem.)",          fr:"superflue",            alts:["superflue"],            needsHyphen:false, needsAccent:false, gender:"f", category:"subjects"},
    {en:"my favourite class is...",    fr:"mon cours préféré est...", alts:["mon cours préféré est...","mon cours préféré est"], needsHyphen:false, needsAccent:true, gender:"m", category:"subjects"},
  
    // ===== AVOIR conjugation (B.5, Page 39) =====
    {en:"to have (infinitive)",        fr:"avoir",                alts:["avoir"],                needsHyphen:false, needsAccent:false, gender:"both", category:"avoir"},
    {en:"I have",                      fr:"j'ai",                 alts:["j'ai"],                 needsHyphen:false, needsAccent:false, gender:"both", category:"avoir"},
    {en:"you have (familiar, singular)", fr:"tu as",              alts:["tu as"],                needsHyphen:false, needsAccent:false, gender:"both", category:"avoir"},
    {en:"he has",                      fr:"il a",                 alts:["il a"],                 needsHyphen:false, needsAccent:false, gender:"m", category:"avoir"},
    {en:"she has",                     fr:"elle a",               alts:["elle a"],               needsHyphen:false, needsAccent:false, gender:"f", category:"avoir"},
    {en:"one has (impersonal)",        fr:"on a",                 alts:["on a"],                 needsHyphen:false, needsAccent:false, gender:"both", category:"avoir"},
    {en:"we have",                     fr:"nous avons",           alts:["nous avons"],           needsHyphen:false, needsAccent:false, gender:"both", category:"avoir"},
    {en:"you have (formal or plural)", fr:"vous avez",            alts:["vous avez"],            needsHyphen:false, needsAccent:false, gender:"both", category:"avoir"},
    {en:"they have (masc. plural)",    fr:"ils ont",              alts:["ils ont"],              needsHyphen:false, needsAccent:false, gender:"m", category:"avoir"},
    {en:"they have (fem. plural)",     fr:"elles ont",            alts:["elles ont"],            needsHyphen:false, needsAccent:false, gender:"f", category:"avoir"},
    {en:"I don't have",                fr:"je n'ai pas",          alts:["je n'ai pas"],          needsHyphen:false, needsAccent:false, gender:"both", category:"avoir"},
    {en:"you don't have (familiar)",   fr:"tu n'as pas",          alts:["tu n'as pas"],          needsHyphen:false, needsAccent:false, gender:"both", category:"avoir"},
    {en:"he doesn't have",             fr:"il n'a pas",           alts:["il n'a pas"],           needsHyphen:false, needsAccent:false, gender:"m", category:"avoir"},
    {en:"she doesn't have",            fr:"elle n'a pas",         alts:["elle n'a pas"],         needsHyphen:false, needsAccent:false, gender:"f", category:"avoir"},
    {en:"one doesn't have (impersonal)", fr:"on n'a pas",         alts:["on n'a pas"],           needsHyphen:false, needsAccent:false, gender:"both", category:"avoir"},
    {en:"we don't have",               fr:"nous n'avons pas",     alts:["nous n'avons pas"],     needsHyphen:false, needsAccent:false, gender:"both", category:"avoir"},
    {en:"you don't have (formal/plural)", fr:"vous n'avez pas",   alts:["vous n'avez pas"],      needsHyphen:false, needsAccent:false, gender:"both", category:"avoir"},
    {en:"they don't have (masc. plural)", fr:"ils n'ont pas",     alts:["ils n'ont pas"],        needsHyphen:false, needsAccent:false, gender:"m", category:"avoir"},
    {en:"they don't have (fem. plural)", fr:"elles n'ont pas",    alts:["elles n'ont pas"],      needsHyphen:false, needsAccent:false, gender:"f", category:"avoir"},
  
    // ===== USEFUL ADDITIONS — Étape 2 =====
    {en:"a bicycle",                   fr:"une bicyclette",       alts:["une bicyclette"],       needsHyphen:false, needsAccent:false, gender:"f", guessGender:true, category:"useful"},
    {en:"then / next",                 fr:"puis",                 alts:["puis"],                 needsHyphen:false, needsAccent:false, gender:"both", category:"useful"},
    {en:"this week",                   fr:"cette semaine",        alts:["cette semaine"],        needsHyphen:false, needsAccent:false, gender:"f", category:"useful"},
    {en:"this month",                  fr:"ce mois",              alts:["ce mois"],              needsHyphen:false, needsAccent:false, gender:"m", category:"useful"},
    {en:"your (familiar, masc.)",      fr:"ton",                  alts:["ton"],                  needsHyphen:false, needsAccent:false, gender:"m", category:"useful"},
    {en:"your (familiar, fem.)",       fr:"ta",                   alts:["ta"],                   needsHyphen:false, needsAccent:false, gender:"f", category:"useful"},

    // ==================================================================
    // PART 2: Class 10 (body parts, hair, eyes, describing, personality,
    //          courses, plurals, avoir additions, people additions, useful additions)
    // ==================================================================
  
    // ===== BODY PARTS (Les parties du corps) =====
    {en:"the mouth",                       fr:"la bouche",          alts:["la bouche"],          needsHyphen:false, needsAccent:false, gender:"f",    guessGender:true, category:"bodyparts"},
    {en:"the arm",                         fr:"le bras",            alts:["le bras"],            needsHyphen:false, needsAccent:false, gender:"m",    guessGender:true, category:"bodyparts"},
    {en:"the hair",                        fr:"les cheveux",        alts:["les cheveux"],        needsHyphen:false, needsAccent:false, gender:"m",    guessGender:true, category:"bodyparts"},
    {en:"the body",                        fr:"le corps",           alts:["le corps"],           needsHyphen:false, needsAccent:false, gender:"m",    guessGender:true, category:"bodyparts"},
    {en:"the back",                        fr:"le dos",             alts:["le dos"],             needsHyphen:false, needsAccent:false, gender:"m",    guessGender:true, category:"bodyparts"},
    {en:"the shoulder",                    fr:"l'épaule",           alts:["l'épaule","l’épaule"], needsHyphen:false, needsAccent:true,  gender:"f",    guessGender:true, category:"bodyparts"},
    {en:"the shoulders",                   fr:"les épaules",        alts:["les épaules"],        needsHyphen:false, needsAccent:true,  gender:"f",    guessGender:true, category:"bodyparts"},
    {en:"the leg",                         fr:"la jambe",           alts:["la jambe"],           needsHyphen:false, needsAccent:false, gender:"f",    guessGender:true, category:"bodyparts"},
    {en:"the hand",                        fr:"la main",            alts:["la main"],            needsHyphen:false, needsAccent:false, gender:"f",    guessGender:true, category:"bodyparts"},
    {en:"the nose",                        fr:"le nez",             alts:["le nez"],             needsHyphen:false, needsAccent:false, gender:"m",    guessGender:true, category:"bodyparts"},
    {en:"the eye",                         fr:"l'œil",              alts:["l'œil","l'oeil","l’œil","l’oeil"], needsHyphen:false, needsAccent:false, gender:"m", guessGender:true, category:"bodyparts"},
    {en:"the eyes",                        fr:"les yeux",           alts:["les yeux"],           needsHyphen:false, needsAccent:false, gender:"m",    guessGender:true, category:"bodyparts"},
    {en:"the ear",                         fr:"l'oreille",          alts:["l'oreille","l’oreille"], needsHyphen:false, needsAccent:false, gender:"f", guessGender:true, category:"bodyparts"},
    {en:"the foot",                        fr:"le pied",            alts:["le pied"],            needsHyphen:false, needsAccent:false, gender:"m",    guessGender:true, category:"bodyparts"},
    {en:"the head",                        fr:"la tête",            alts:["la tête"],            needsHyphen:false, needsAccent:true,  gender:"f",    guessGender:true, category:"bodyparts"},
    {en:"the stomach/belly",               fr:"le ventre",          alts:["le ventre"],          needsHyphen:false, needsAccent:false, gender:"m",    guessGender:true, category:"bodyparts"},
    {en:"the face",                        fr:"le visage",          alts:["le visage"],          needsHyphen:false, needsAccent:false, gender:"m",    guessGender:true, category:"bodyparts"},
    {en:"a beard",                         fr:"une barbe",          alts:["une barbe"],          needsHyphen:false, needsAccent:false, gender:"f",    guessGender:true, category:"bodyparts"},
    {en:"a moustache",                     fr:"une moustache",      alts:["une moustache"],      needsHyphen:false, needsAccent:false, gender:"f",    guessGender:true, category:"bodyparts"},
    {en:"glasses",                         fr:"des lunettes",       alts:["des lunettes"],       needsHyphen:false, needsAccent:false, gender:"f",    guessGender:true, category:"bodyparts"},
    {en:"contact lenses",                  fr:"des lentilles de contact", alts:["des lentilles de contact","des lentilles"], needsHyphen:false, needsAccent:false, gender:"f", guessGender:true, category:"bodyparts"},
  
    // ===== HAIR — colour & style =====
    {en:"blond hair",                      fr:"les cheveux blonds", alts:["les cheveux blonds"], needsHyphen:false, needsAccent:false, gender:"m", category:"hair"},
    {en:"brown hair",                      fr:"les cheveux bruns",  alts:["les cheveux bruns"],  needsHyphen:false, needsAccent:false, gender:"m", category:"hair"},
    {en:"light brown / chestnut hair",     fr:"les cheveux châtains", alts:["les cheveux châtains"], needsHyphen:false, needsAccent:true, gender:"m", category:"hair"},
    {en:"black hair",                      fr:"les cheveux noirs",  alts:["les cheveux noirs"],  needsHyphen:false, needsAccent:false, gender:"m", category:"hair"},
    {en:"red hair",                        fr:"les cheveux roux",   alts:["les cheveux roux"],   needsHyphen:false, needsAccent:false, gender:"m", category:"hair"},
    {en:"short hair",                      fr:"les cheveux courts", alts:["les cheveux courts"], needsHyphen:false, needsAccent:false, gender:"m", category:"hair"},
    {en:"medium-length hair",              fr:"les cheveux mi-longs", alts:["les cheveux mi-longs"], needsHyphen:true, needsAccent:false, gender:"m", category:"hair"},
    {en:"long hair",                       fr:"les cheveux longs",  alts:["les cheveux longs"],  needsHyphen:false, needsAccent:false, gender:"m", category:"hair"},
    {en:"curly hair",                      fr:"les cheveux frisés", alts:["les cheveux frisés"], needsHyphen:false, needsAccent:true,  gender:"m", category:"hair"},
    {en:"a redhead (masc.)",               fr:"roux",               alts:["roux"],               needsHyphen:false, needsAccent:false, gender:"m", category:"hair"},
    {en:"a redhead (fem.)",                fr:"rousse",             alts:["rousse"],             needsHyphen:false, needsAccent:false, gender:"f", category:"hair"},
    {en:"blond (masc.)",                   fr:"blond",              alts:["blond"],              needsHyphen:false, needsAccent:false, gender:"m", category:"hair"},
    {en:"blond (fem.)",                    fr:"blonde",             alts:["blonde"],             needsHyphen:false, needsAccent:false, gender:"f", category:"hair"},
    {en:"brown-haired (masc.)",            fr:"brun",               alts:["brun"],               needsHyphen:false, needsAccent:false, gender:"m", category:"hair"},
    {en:"brown-haired (fem.)",             fr:"brune",              alts:["brune"],              needsHyphen:false, needsAccent:false, gender:"f", category:"hair"},
  
    // ===== EYES — colour =====
    {en:"blue eyes",                       fr:"les yeux bleus",     alts:["les yeux bleus"],     needsHyphen:false, needsAccent:false, gender:"m", category:"eyes"},
    {en:"brown eyes",                      fr:"les yeux marron",    alts:["les yeux marron"],    needsHyphen:false, needsAccent:false, gender:"m", category:"eyes"},
    {en:"green eyes",                      fr:"les yeux verts",     alts:["les yeux verts"],     needsHyphen:false, needsAccent:false, gender:"m", category:"eyes"},
    {en:"black eyes",                      fr:"les yeux noirs",     alts:["les yeux noirs"],     needsHyphen:false, needsAccent:false, gender:"m", category:"eyes"},
    {en:"grey eyes",                       fr:"les yeux gris",      alts:["les yeux gris"],      needsHyphen:false, needsAccent:false, gender:"m", category:"eyes"},
  
    // ===== DESCRIBE — physical & general adjectives =====
    {en:"tall, big (masc.)",               fr:"grand",              alts:["grand"],              needsHyphen:false, needsAccent:false, gender:"m", category:"describe"},
    {en:"tall, big (fem.)",                fr:"grande",             alts:["grande"],             needsHyphen:false, needsAccent:false, gender:"f", category:"describe"},
    {en:"small, short (masc.)",            fr:"petit",              alts:["petit"],              needsHyphen:false, needsAccent:false, gender:"m", category:"describe"},
    {en:"small, short (fem.)",             fr:"petite",             alts:["petite"],             needsHyphen:false, needsAccent:false, gender:"f", category:"describe"},
    {en:"thin/slim (invariable)",          fr:"mince",              alts:["mince"],              needsHyphen:false, needsAccent:false, gender:"both", category:"describe"},
    {en:"of medium height",                fr:"de taille moyenne",  alts:["de taille moyenne"],  needsHyphen:false, needsAccent:false, gender:"both", category:"describe"},
    {en:"handsome / beautiful (masc.)",    fr:"beau",               alts:["beau"],               needsHyphen:false, needsAccent:false, gender:"m", category:"describe"},
    {en:"beautiful (fem.)",                fr:"belle",              alts:["belle"],              needsHyphen:false, needsAccent:false, gender:"f", category:"describe"},
    {en:"handsome (before vowel/mute h)",  fr:"bel",                alts:["bel"],                needsHyphen:false, needsAccent:false, gender:"m", category:"describe"},
    {en:"ugly (masc.)",                    fr:"laid",               alts:["laid"],               needsHyphen:false, needsAccent:false, gender:"m", category:"describe"},
    {en:"ugly (fem.)",                     fr:"laide",              alts:["laide"],              needsHyphen:false, needsAccent:false, gender:"f", category:"describe"},
    {en:"old, elderly (masc.)",            fr:"vieux",              alts:["vieux"],              needsHyphen:false, needsAccent:false, gender:"m", category:"describe"},
    {en:"old, elderly (fem.)",             fr:"vieille",            alts:["vieille"],            needsHyphen:false, needsAccent:false, gender:"f", category:"describe"},
    {en:"old (before vowel/mute h)",       fr:"vieil",              alts:["vieil"],              needsHyphen:false, needsAccent:false, gender:"m", category:"describe"},
    {en:"new (masc.)",                     fr:"nouveau",            alts:["nouveau"],            needsHyphen:false, needsAccent:false, gender:"m", category:"describe"},
    {en:"new (fem.)",                      fr:"nouvelle",           alts:["nouvelle"],           needsHyphen:false, needsAccent:false, gender:"f", category:"describe"},
    {en:"new (before vowel/mute h)",       fr:"nouvel",             alts:["nouvel"],             needsHyphen:false, needsAccent:false, gender:"m", category:"describe"},
    {en:"good (masc.)",                    fr:"bon",                alts:["bon"],                needsHyphen:false, needsAccent:false, gender:"m", category:"describe"},
    {en:"good (fem.)",                     fr:"bonne",              alts:["bonne"],              needsHyphen:false, needsAccent:false, gender:"f", category:"describe"},
    {en:"bad (masc.)",                     fr:"mauvais",            alts:["mauvais"],            needsHyphen:false, needsAccent:false, gender:"m", category:"describe"},
    {en:"bad (fem.)",                      fr:"mauvaise",           alts:["mauvaise"],           needsHyphen:false, needsAccent:false, gender:"f", category:"describe"},
    {en:"ancient, antique (masc.)",        fr:"ancien",             alts:["ancien"],             needsHyphen:false, needsAccent:false, gender:"m", category:"describe"},
    {en:"ancient, antique (fem.)",         fr:"ancienne",           alts:["ancienne"],           needsHyphen:false, needsAccent:false, gender:"f", category:"describe"},
    {en:"long (masc.)",                    fr:"long",               alts:["long"],               needsHyphen:false, needsAccent:false, gender:"m", category:"describe"},
    {en:"long (fem.)",                     fr:"longue",             alts:["longue"],             needsHyphen:false, needsAccent:false, gender:"f", category:"describe"},
    {en:"tired (masc.)",                   fr:"fatigué",            alts:["fatigué"],            needsHyphen:false, needsAccent:true,  gender:"m", category:"describe"},
    {en:"tired (fem.)",                    fr:"fatiguée",           alts:["fatiguée"],           needsHyphen:false, needsAccent:true,  gender:"f", category:"describe"},
    {en:"easy",                            fr:"facile",             alts:["facile"],             needsHyphen:false, needsAccent:false, gender:"both", category:"describe"},
    {en:"difficult",                       fr:"difficile",          alts:["difficile"],          needsHyphen:false, needsAccent:false, gender:"both", category:"describe"},
    {en:"useful",                          fr:"utile",              alts:["utile"],              needsHyphen:false, needsAccent:false, gender:"both", category:"describe"},
    {en:"useless",                         fr:"inutile",            alts:["inutile"],            needsHyphen:false, needsAccent:false, gender:"both", category:"describe"},
    {en:"boring (masc.)",                  fr:"ennuyeux",           alts:["ennuyeux"],           needsHyphen:false, needsAccent:false, gender:"m", category:"describe"},
    {en:"boring (fem.)",                   fr:"ennuyeuse",          alts:["ennuyeuse"],          needsHyphen:false, needsAccent:false, gender:"f", category:"describe"},
    {en:"exciting / passionate (masc.)",   fr:"passionnant",        alts:["passionnant"],        needsHyphen:false, needsAccent:false, gender:"m", category:"describe"},
    {en:"exciting / passionate (fem.)",    fr:"passionnante",       alts:["passionnante"],       needsHyphen:false, needsAccent:false, gender:"f", category:"describe"},
    {en:"funny (masc.)",                   fr:"amusant",            alts:["amusant"],            needsHyphen:false, needsAccent:false, gender:"m", category:"describe"},
    {en:"funny (fem.)",                    fr:"amusante",           alts:["amusante"],           needsHyphen:false, needsAccent:false, gender:"f", category:"describe"},
    {en:"interesting (masc.)",             fr:"intéressant",        alts:["intéressant"],        needsHyphen:false, needsAccent:true,  gender:"m", category:"describe"},
    {en:"interesting (fem.)",              fr:"intéressante",       alts:["intéressante"],       needsHyphen:false, needsAccent:true,  gender:"f", category:"describe"},
    {en:"abstract (masc.)",                fr:"abstrait",           alts:["abstrait"],           needsHyphen:false, needsAccent:false, gender:"m", category:"describe"},
    {en:"abstract (fem.)",                 fr:"abstraite",          alts:["abstraite"],          needsHyphen:false, needsAccent:false, gender:"f", category:"describe"},
    {en:"complicated (masc.)",             fr:"compliqué",          alts:["compliqué"],          needsHyphen:false, needsAccent:true,  gender:"m", category:"describe"},
    {en:"complicated (fem.)",              fr:"compliquée",         alts:["compliquée"],         needsHyphen:false, needsAccent:true,  gender:"f", category:"describe"},
    {en:"important (masc.)",               fr:"important",          alts:["important"],          needsHyphen:false, needsAccent:false, gender:"m", category:"describe"},
    {en:"important (fem.)",                fr:"importante",         alts:["importante"],         needsHyphen:false, needsAccent:false, gender:"f", category:"describe"},
    {en:"practical (masc.)",               fr:"pratique",           alts:["pratique"],           needsHyphen:false, needsAccent:false, gender:"both", category:"describe"},
    {en:"superfluous (masc.)",             fr:"superflu",           alts:["superflu"],           needsHyphen:false, needsAccent:false, gender:"m", category:"describe"},
    {en:"superfluous (fem.)",              fr:"superflue",          alts:["superflue"],          needsHyphen:false, needsAccent:false, gender:"f", category:"describe"},
    {en:"sporty (masc.)",                  fr:"sportif",            alts:["sportif"],            needsHyphen:false, needsAccent:false, gender:"m", category:"describe"},
    {en:"sporty (fem.)",                   fr:"sportive",           alts:["sportive"],           needsHyphen:false, needsAccent:false, gender:"f", category:"describe"},
    {en:"studious (masc.)",                fr:"studieux",           alts:["studieux"],           needsHyphen:false, needsAccent:false, gender:"m", category:"describe"},
    {en:"studious (fem.)",                 fr:"studieuse",          alts:["studieuse"],          needsHyphen:false, needsAccent:false, gender:"f", category:"describe"},
    {en:"generous (masc.)",                fr:"généreux",           alts:["généreux"],           needsHyphen:false, needsAccent:true,  gender:"m", category:"describe"},
    {en:"generous (fem.)",                 fr:"généreuse",          alts:["généreuse"],          needsHyphen:false, needsAccent:true,  gender:"f", category:"describe"},
    {en:"nervous (masc.)",                 fr:"nerveux",            alts:["nerveux"],            needsHyphen:false, needsAccent:false, gender:"m", category:"describe"},
    {en:"nervous (fem.)",                  fr:"nerveuse",           alts:["nerveuse"],           needsHyphen:false, needsAccent:false, gender:"f", category:"describe"},
    {en:"dangerous (masc.)",               fr:"dangereux",          alts:["dangereux"],          needsHyphen:false, needsAccent:false, gender:"m", category:"describe"},
    {en:"dangerous (fem.)",                fr:"dangereuse",         alts:["dangereuse"],         needsHyphen:false, needsAccent:false, gender:"f", category:"describe"},
    {en:"mysterious (masc.)",              fr:"mystérieux",         alts:["mystérieux"],         needsHyphen:false, needsAccent:true,  gender:"m", category:"describe"},
    {en:"mysterious (fem.)",               fr:"mystérieuse",        alts:["mystérieuse"],        needsHyphen:false, needsAccent:true,  gender:"f", category:"describe"},
    {en:"patient (masc.)",                 fr:"patient",            alts:["patient"],            needsHyphen:false, needsAccent:false, gender:"m", category:"describe"},
    {en:"patient (fem.)",                  fr:"patiente",           alts:["patiente"],           needsHyphen:false, needsAccent:false, gender:"f", category:"describe"},
    {en:"individualistic",                 fr:"individualiste",     alts:["individualiste"],     needsHyphen:false, needsAccent:false, gender:"both", category:"describe"},
  
    // ===== PERSONALITY (Mots apparentés — invariable / regular) =====
    {en:"selfish",                         fr:"égoïste",            alts:["égoïste"],            needsHyphen:false, needsAccent:true,  gender:"both", category:"personality"},
    {en:"sensible / reasonable",           fr:"raisonnable",        alts:["raisonnable"],        needsHyphen:false, needsAccent:false, gender:"both", category:"personality"},
    {en:"nice",                            fr:"sympathique",        alts:["sympathique"],        needsHyphen:false, needsAccent:false, gender:"both", category:"personality"},
    {en:"funny / amusing (masc.)",         fr:"amusant",            alts:["amusant"],            needsHyphen:false, needsAccent:false, gender:"m", category:"personality"},
    {en:"funny / amusing (fem.)",          fr:"amusante",           alts:["amusante"],           needsHyphen:false, needsAccent:false, gender:"f", category:"personality"},
    {en:"courageous (masc.)",              fr:"courageux",          alts:["courageux"],          needsHyphen:false, needsAccent:false, gender:"m", category:"personality"},
    {en:"courageous (fem.)",               fr:"courageuse",         alts:["courageuse"],         needsHyphen:false, needsAccent:false, gender:"f", category:"personality"},
    {en:"dynamic",                         fr:"dynamique",          alts:["dynamique"],          needsHyphen:false, needsAccent:false, gender:"both", category:"personality"},
    {en:"enthusiastic",                    fr:"enthousiaste",       alts:["enthousiaste"],       needsHyphen:false, needsAccent:false, gender:"both", category:"personality"},
    {en:"idealistic",                      fr:"idéaliste",          alts:["idéaliste"],          needsHyphen:false, needsAccent:true,  gender:"both", category:"personality"},
    {en:"intelligent (masc.)",             fr:"intelligent",        alts:["intelligent"],        needsHyphen:false, needsAccent:false, gender:"m", category:"personality"},
    {en:"intelligent (fem.)",              fr:"intelligente",       alts:["intelligente"],       needsHyphen:false, needsAccent:false, gender:"f", category:"personality"},
    {en:"optimistic",                      fr:"optimiste",          alts:["optimiste"],          needsHyphen:false, needsAccent:false, gender:"both", category:"personality"},
    {en:"pessimistic",                     fr:"pessimiste",         alts:["pessimiste"],         needsHyphen:false, needsAccent:false, gender:"both", category:"personality"},
    {en:"cautious / prudent (masc.)",      fr:"prudent",            alts:["prudent"],            needsHyphen:false, needsAccent:false, gender:"m", category:"personality"},
    {en:"cautious / prudent (fem.)",       fr:"prudente",           alts:["prudente"],           needsHyphen:false, needsAccent:false, gender:"f", category:"personality"},
    {en:"resolute / determined (masc.)",   fr:"résolu",             alts:["résolu"],             needsHyphen:false, needsAccent:true,  gender:"m", category:"personality"},
    {en:"resolute / determined (fem.)",    fr:"résolue",            alts:["résolue"],            needsHyphen:false, needsAccent:true,  gender:"f", category:"personality"},
    {en:"serious (masc.)",                 fr:"sérieux",            alts:["sérieux"],            needsHyphen:false, needsAccent:true,  gender:"m", category:"personality"},
    {en:"serious (fem.)",                  fr:"sérieuse",           alts:["sérieuse"],           needsHyphen:false, needsAccent:true,  gender:"f", category:"personality"},
    {en:"sociable",                        fr:"sociable",           alts:["sociable"],           needsHyphen:false, needsAccent:false, gender:"both", category:"personality"},
    {en:"shy / timid",                     fr:"timide",             alts:["timide"],             needsHyphen:false, needsAccent:false, gender:"both", category:"personality"},
  
    // ===== COURSES (Les cours) =====
    {en:"drawing / graphic arts",          fr:"le dessin",          alts:["le dessin"],          needsHyphen:false, needsAccent:false, gender:"m", guessGender:true, category:"courses"},
    {en:"literature",                      fr:"la littérature",     alts:["la littérature"],     needsHyphen:false, needsAccent:true,  gender:"f", guessGender:true, category:"courses"},
    {en:"gymnastics / PE",                 fr:"la gymnastique",     alts:["la gymnastique"],     needsHyphen:false, needsAccent:false, gender:"f", guessGender:true, category:"courses"},
    {en:"chemistry",                       fr:"la chimie",          alts:["la chimie"],          needsHyphen:false, needsAccent:false, gender:"f", guessGender:true, category:"courses"},
    {en:"geography",                       fr:"la géographie",      alts:["la géographie"],      needsHyphen:false, needsAccent:true,  gender:"f", guessGender:true, category:"courses"},
    {en:"economics",                       fr:"l'économie",         alts:["l'économie","l’économie"], needsHyphen:false, needsAccent:true,  gender:"f", guessGender:true, category:"courses"},
    {en:"marketing",                       fr:"le marketing",       alts:["le marketing"],       needsHyphen:false, needsAccent:false, gender:"m", guessGender:true, category:"courses"},
    {en:"physics",                         fr:"la physique",        alts:["la physique"],        needsHyphen:false, needsAccent:false, gender:"f", guessGender:true, category:"courses"},
    {en:"biology",                         fr:"la biologie",        alts:["la biologie"],        needsHyphen:false, needsAccent:false, gender:"f", guessGender:true, category:"courses"},
    {en:"sociology",                       fr:"la sociologie",      alts:["la sociologie"],      needsHyphen:false, needsAccent:false, gender:"f", guessGender:true, category:"courses"},
    {en:"math / mathematics",              fr:"les mathématiques",  alts:["les mathématiques","les maths"], needsHyphen:false, needsAccent:true,  gender:"f", guessGender:true, category:"courses"},
    {en:"history",                         fr:"l'histoire",         alts:["l'histoire","l’histoire"], needsHyphen:false, needsAccent:false, gender:"f", guessGender:true, category:"courses"},
    {en:"theatre",                         fr:"le théâtre",         alts:["le théâtre"],         needsHyphen:false, needsAccent:true,  gender:"m", guessGender:true, category:"courses"},
    {en:"computer science",                fr:"l'informatique",     alts:["l'informatique","l’informatique"], needsHyphen:false, needsAccent:false, gender:"f", guessGender:true, category:"courses"},
    {en:"music",                           fr:"la musique",         alts:["la musique"],         needsHyphen:false, needsAccent:false, gender:"f", guessGender:true, category:"courses"},
    {en:"psychology",                      fr:"la psychologie",     alts:["la psychologie"],     needsHyphen:false, needsAccent:false, gender:"f", guessGender:true, category:"courses"},
    {en:"civil engineering",               fr:"le génie civil",     alts:["le génie civil"],     needsHyphen:false, needsAccent:true,  gender:"m", guessGender:true, category:"courses"},
    {en:"performing arts",                 fr:"les arts du spectacle", alts:["les arts du spectacle"], needsHyphen:false, needsAccent:false, gender:"m", guessGender:true, category:"courses"},
    {en:"fine arts",                       fr:"les beaux-arts",     alts:["les beaux-arts"],     needsHyphen:true,  needsAccent:false, gender:"m", guessGender:true, category:"courses"},
    {en:"accounting",                      fr:"la comptabilité",    alts:["la comptabilité"],    needsHyphen:false, needsAccent:true,  gender:"f", guessGender:true, category:"courses"},
    {en:"French (the language)",           fr:"le français",        alts:["le français"],        needsHyphen:false, needsAccent:true,  gender:"m", guessGender:true, category:"courses"},
    {en:"advertising",                     fr:"la publicité",       alts:["la publicité"],       needsHyphen:false, needsAccent:true,  gender:"f", guessGender:true, category:"courses"},
    {en:"philosophy",                      fr:"la philosophie",     alts:["la philosophie"],     needsHyphen:false, needsAccent:false, gender:"f", guessGender:true, category:"courses"},
    {en:"geology",                         fr:"la géologie",        alts:["la géologie"],        needsHyphen:false, needsAccent:true,  gender:"f", guessGender:true, category:"courses"},
    {en:"art history",                     fr:"l'histoire de l'art",alts:["l'histoire de l'art","l’histoire de l’art"], needsHyphen:false, needsAccent:false, gender:"f", guessGender:true, category:"courses"},
  
    // ===== AVOIR — conjugation & possession =====
    {en:"to have (infinitive)",            fr:"avoir",              alts:["avoir"],              needsHyphen:false, needsAccent:false, gender:"both", category:"avoir"},
    {en:"I have",                          fr:"j'ai",               alts:["j'ai","j’ai"],        needsHyphen:false, needsAccent:false, gender:"both", category:"avoir"},
    {en:"you have (familiar)",             fr:"tu as",              alts:["tu as"],              needsHyphen:false, needsAccent:false, gender:"both", category:"avoir"},
    {en:"he has",                          fr:"il a",               alts:["il a"],               needsHyphen:false, needsAccent:false, gender:"m", category:"avoir"},
    {en:"she has",                         fr:"elle a",             alts:["elle a"],             needsHyphen:false, needsAccent:false, gender:"f", category:"avoir"},
    {en:"one has (impersonal)",            fr:"on a",               alts:["on a"],               needsHyphen:false, needsAccent:false, gender:"both", category:"avoir"},
    {en:"we have",                         fr:"nous avons",         alts:["nous avons"],         needsHyphen:false, needsAccent:false, gender:"both", category:"avoir"},
    {en:"you have (formal/plural)",        fr:"vous avez",          alts:["vous avez"],          needsHyphen:false, needsAccent:false, gender:"both", category:"avoir"},
    {en:"they have (masc.)",               fr:"ils ont",            alts:["ils ont"],            needsHyphen:false, needsAccent:false, gender:"m", category:"avoir"},
    {en:"they have (fem.)",                fr:"elles ont",          alts:["elles ont"],          needsHyphen:false, needsAccent:false, gender:"f", category:"avoir"},
    {en:"I don't have",                    fr:"je n'ai pas",        alts:["je n'ai pas","je n’ai pas"], needsHyphen:false, needsAccent:false, gender:"both", category:"avoir"},
    {en:"you don't have (familiar)",       fr:"tu n'as pas",        alts:["tu n'as pas","tu n’as pas"], needsHyphen:false, needsAccent:false, gender:"both", category:"avoir"},
    {en:"he doesn't have",                 fr:"il n'a pas",         alts:["il n'a pas","il n’a pas"], needsHyphen:false, needsAccent:false, gender:"m", category:"avoir"},
    {en:"she doesn't have",                fr:"elle n'a pas",       alts:["elle n'a pas","elle n’a pas"], needsHyphen:false, needsAccent:false, gender:"f", category:"avoir"},
    {en:"we don't have",                   fr:"nous n'avons pas",   alts:["nous n'avons pas","nous n’avons pas"], needsHyphen:false, needsAccent:false, gender:"both", category:"avoir"},
    {en:"you don't have (formal/plural)",  fr:"vous n'avez pas",    alts:["vous n'avez pas","vous n’avez pas"], needsHyphen:false, needsAccent:false, gender:"both", category:"avoir"},
    {en:"they don't have (masc.)",         fr:"ils n'ont pas",      alts:["ils n'ont pas","ils n’ont pas"], needsHyphen:false, needsAccent:false, gender:"m", category:"avoir"},
    {en:"they don't have (fem.)",          fr:"elles n'ont pas",    alts:["elles n'ont pas","elles n’ont pas"], needsHyphen:false, needsAccent:false, gender:"f", category:"avoir"},
    {en:"What class/course do you have?",  fr:"Quel cours as-tu ?", alts:["Quel cours as-tu","Quel cours as-tu ?","Quel cours as-tu?"], needsHyphen:true, needsAccent:false, gender:"both", category:"avoir"},
    {en:"What class do you have? (formal/pl.)", fr:"Quel cours avez-vous ?", alts:["Quel cours avez-vous","Quel cours avez-vous ?","Quel cours avez-vous?"], needsHyphen:true, needsAccent:false, gender:"both", category:"avoir"},
    {en:"I have a French class.",          fr:"J'ai un cours de français.", alts:["J'ai un cours de français","J'ai un cours de français.","J’ai un cours de français."], needsHyphen:false, needsAccent:true, gender:"both", category:"avoir"},
  
    // ===== NOUNS (Substantifs) =====
    {en:"an actor",                        fr:"un acteur",          alts:["un acteur"],          needsHyphen:false, needsAccent:false, gender:"m", guessGender:true, category:"people"},
    {en:"an actress",                      fr:"une actrice",        alts:["une actrice"],        needsHyphen:false, needsAccent:false, gender:"f", guessGender:true, category:"people"},
    {en:"a man",                           fr:"un homme",           alts:["un homme"],           needsHyphen:false, needsAccent:false, gender:"m", guessGender:true, category:"people"},
    {en:"a woman",                         fr:"une femme",          alts:["une femme"],          needsHyphen:false, needsAccent:false, gender:"f", guessGender:true, category:"people"},
    {en:"a gentleman / sir",               fr:"un monsieur",        alts:["un monsieur"],        needsHyphen:false, needsAccent:false, gender:"m", guessGender:true, category:"people"},
    {en:"a lady",                          fr:"une dame",           alts:["une dame"],           needsHyphen:false, needsAccent:false, gender:"f", guessGender:true, category:"people"},
    {en:"a boy",                           fr:"un garçon",          alts:["un garçon"],          needsHyphen:false, needsAccent:false, gender:"m", guessGender:true, category:"people"},
    {en:"a girl",                          fr:"une fille",          alts:["une fille"],          needsHyphen:false, needsAccent:false, gender:"f", guessGender:true, category:"people"},
    {en:"a student (masc.)",               fr:"un étudiant",        alts:["un étudiant"],        needsHyphen:false, needsAccent:true,  gender:"m", guessGender:true, category:"people"},
    {en:"a student (fem.)",                fr:"une étudiante",      alts:["une étudiante"],      needsHyphen:false, needsAccent:true,  gender:"f", guessGender:true, category:"people"},
    {en:"a teacher / professor",           fr:"un professeur",      alts:["un professeur","une professeur","une professeure"], needsHyphen:false, needsAccent:false, gender:"m", guessGender:true, category:"people"},
    {en:"people",                          fr:"les gens",           alts:["les gens"],           needsHyphen:false, needsAccent:false, gender:"m", category:"people"},
    {en:"a friend (masc.)",                fr:"un ami",             alts:["un ami"],             needsHyphen:false, needsAccent:false, gender:"m", guessGender:true, category:"people"},
    {en:"a friend (fem.)",                 fr:"une amie",           alts:["une amie"],           needsHyphen:false, needsAccent:false, gender:"f", guessGender:true, category:"people"},
    {en:"a celebrity / star",              fr:"une vedette",        alts:["une vedette"],        needsHyphen:false, needsAccent:false, gender:"f", guessGender:true, category:"people"},
    {en:"a CEO",                           fr:"un PDG",             alts:["un PDG","une PDG"],   needsHyphen:false, needsAccent:false, gender:"both", category:"people"},
    {en:"a poet (masc.)",                  fr:"un poète",           alts:["un poète"],           needsHyphen:false, needsAccent:true,  gender:"m", guessGender:true, category:"people"},
    {en:"a poet (fem.)",                   fr:"une poète",          alts:["une poète","une poétesse"], needsHyphen:false, needsAccent:true,  gender:"f", guessGender:true, category:"people"},
    {en:"a cyclist",                       fr:"un cycliste",        alts:["un cycliste","une cycliste"], needsHyphen:false, needsAccent:false, gender:"both", category:"people"},
    {en:"my favourite actor",              fr:"mon acteur préféré", alts:["mon acteur préféré"], needsHyphen:false, needsAccent:true,  gender:"m", category:"people"},
    {en:"my favourite actress",            fr:"mon actrice préférée", alts:["mon actrice préférée"], needsHyphen:false, needsAccent:true,  gender:"f", category:"people"},
  
    // ===== OTHER NOUNS / VOCAB =====
    {en:"love",                            fr:"l'amour",            alts:["l'amour","l’amour"],  needsHyphen:false, needsAccent:false, gender:"m", guessGender:true, category:"useful"},
    {en:"a birthday",                      fr:"un anniversaire",    alts:["un anniversaire"],    needsHyphen:false, needsAccent:false, gender:"m", guessGender:true, category:"useful"},
    {en:"a bedroom",                       fr:"une chambre",        alts:["une chambre"],        needsHyphen:false, needsAccent:false, gender:"f", guessGender:true, category:"useful"},
    {en:"an exam",                         fr:"un examen",          alts:["un examen"],          needsHyphen:false, needsAccent:false, gender:"m", guessGender:true, category:"useful"},
    {en:"a quiz",                          fr:"une interrogation",  alts:["une interrogation"],  needsHyphen:false, needsAccent:false, gender:"f", guessGender:true, category:"useful"},
    {en:"lights",                          fr:"les lumières",       alts:["les lumières"],       needsHyphen:false, needsAccent:true,  gender:"f", category:"useful"},
    {en:"an object",                       fr:"un objet",           alts:["un objet"],           needsHyphen:false, needsAccent:false, gender:"m", guessGender:true, category:"useful"},
    {en:"a semester",                      fr:"un semestre",        alts:["un semestre"],        needsHyphen:false, needsAccent:false, gender:"m", guessGender:true, category:"useful"},
    {en:"an opinion",                      fr:"une opinion",        alts:["une opinion"],        needsHyphen:false, needsAccent:false, gender:"f", guessGender:true, category:"useful"},
    {en:"a description",                   fr:"une description",    alts:["une description"],    needsHyphen:false, needsAccent:false, gender:"f", guessGender:true, category:"useful"},
    {en:"a dialogue",                      fr:"un dialogue",        alts:["un dialogue"],        needsHyphen:false, needsAccent:false, gender:"m", guessGender:true, category:"useful"},
    {en:"a letter (of the alphabet)",      fr:"une lettre de l'alphabet", alts:["une lettre de l'alphabet","une lettre de l’alphabet"], needsHyphen:false, needsAccent:false, gender:"f", category:"useful"},
  
    // ===== DESCRIPTION (small adjectives) =====
    {en:"digital",                         fr:"numérique",          alts:["numérique"],          needsHyphen:false, needsAccent:true,  gender:"both", category:"describe"},
    {en:"open (masc.)",                    fr:"ouvert",             alts:["ouvert"],             needsHyphen:false, needsAccent:false, gender:"m", category:"describe"},
    {en:"open (fem.)",                     fr:"ouverte",            alts:["ouverte"],            needsHyphen:false, needsAccent:false, gender:"f", category:"describe"},
    {en:"favourite (masc.)",               fr:"préféré",            alts:["préféré"],            needsHyphen:false, needsAccent:true,  gender:"m", category:"describe"},
    {en:"favourite (fem.)",                fr:"préférée",           alts:["préférée"],           needsHyphen:false, needsAccent:true,  gender:"f", category:"describe"},
    {en:"first (masc.)",                   fr:"premier",            alts:["premier"],            needsHyphen:false, needsAccent:false, gender:"m", category:"describe"},
    {en:"first (fem.)",                    fr:"première",           alts:["première"],           needsHyphen:false, needsAccent:true,  gender:"f", category:"describe"},
  
    // ===== USEFUL WORDS / EXPRESSIONS =====
    {en:"See you tomorrow.",               fr:"À demain.",          alts:["À demain","À demain."], needsHyphen:false, needsAccent:true,  gender:"both", category:"useful"},
    {en:"after",                           fr:"après",              alts:["après"],              needsHyphen:false, needsAccent:true,  gender:"both", category:"useful"},
    {en:"You're welcome.",                 fr:"De rien.",           alts:["De rien","De rien."], needsHyphen:false, needsAccent:false, gender:"both", category:"useful"},
    {en:"same",                            fr:"même",               alts:["même"],               needsHyphen:false, needsAccent:true,  gender:"both", category:"useful"},
    {en:"Thank you.",                      fr:"Merci.",             alts:["Merci","Merci."],     needsHyphen:false, needsAccent:false, gender:"both", category:"useful"},
    {en:"Which course? / What course?",    fr:"Quel cours ?",       alts:["Quel cours","Quel cours ?","Quel cours?"], needsHyphen:false, needsAccent:false, gender:"both", category:"useful"},
    {en:"What is your opinion on... ?",    fr:"Quelle est votre opinion sur... ?", alts:["Quelle est votre opinion sur...","Quelle est votre opinion sur","Quelle est votre opinion sur ?"], needsHyphen:false, needsAccent:false, gender:"both", category:"useful"},
    {en:"Please. (familiar)",              fr:"S'il te plaît.",     alts:["S'il te plaît","S'il te plaît.","S’il te plaît."], needsHyphen:false, needsAccent:true,  gender:"both", category:"useful"},
    {en:"Please. (formal/plural)",         fr:"S'il vous plaît.",   alts:["S'il vous plaît","S'il vous plaît.","S’il vous plaît."], needsHyphen:false, needsAccent:true,  gender:"both", category:"useful"},
    {en:"on",                              fr:"sur",                alts:["sur"],                needsHyphen:false, needsAccent:false, gender:"both", category:"useful"},
    {en:"What hair colour does she have?", fr:"Elle a les cheveux de quelle couleur ?", alts:["Elle a les cheveux de quelle couleur","Elle a les cheveux de quelle couleur ?","Elle a les cheveux de quelle couleur?"], needsHyphen:false, needsAccent:false, gender:"f", category:"useful"},
    {en:"What hair colour does he have?",  fr:"Il a les cheveux de quelle couleur ?", alts:["Il a les cheveux de quelle couleur","Il a les cheveux de quelle couleur ?","Il a les cheveux de quelle couleur?"], needsHyphen:false, needsAccent:false, gender:"m", category:"useful"},
    {en:"What does her hair look like?",   fr:"Elle a les cheveux comment ?", alts:["Elle a les cheveux comment","Elle a les cheveux comment ?","Elle a les cheveux comment?"], needsHyphen:false, needsAccent:false, gender:"f", category:"useful"},
    {en:"Does she have long hair?",        fr:"Est-ce qu'elle a les cheveux longs ?", alts:["Est-ce qu'elle a les cheveux longs","Est-ce qu'elle a les cheveux longs ?","Est-ce qu’elle a les cheveux longs ?"], needsHyphen:true, needsAccent:false, gender:"f", category:"useful"},
    {en:"What eye colour does she have?",  fr:"Elle a les yeux de quelle couleur ?", alts:["Elle a les yeux de quelle couleur","Elle a les yeux de quelle couleur ?"], needsHyphen:false, needsAccent:false, gender:"f", category:"useful"},
    {en:"What is she wearing? / What does she have?", fr:"Qu'est-ce qu'elle porte ?", alts:["Qu'est-ce qu'elle porte","Qu'est-ce qu'elle porte ?","Qu’est-ce qu’elle porte ?"], needsHyphen:true, needsAccent:false, gender:"f", category:"useful"},
    {en:"What is his/her name? (actor)",   fr:"Comment s'appelle ton acteur préféré ?", alts:["Comment s'appelle ton acteur préféré","Comment s'appelle ton acteur préféré ?"], needsHyphen:true, needsAccent:true, gender:"m", category:"useful"},
    {en:"What kind of person is he/she?",  fr:"C'est quel type de personne ?", alts:["C'est quel type de personne","C'est quel type de personne ?","C’est quel type de personne ?"], needsHyphen:false, needsAccent:false, gender:"both", category:"useful"},
    {en:"How is he/she physically?",       fr:"Comment est-il/elle physiquement ?", alts:["Comment est-il/elle physiquement","Comment est-il/elle physiquement ?"], needsHyphen:true, needsAccent:false, gender:"both", category:"useful"},
  
    // ===== IRREGULAR PLURALS (B.7) — key examples =====
    {en:"newspapers (pl. of journal)",     fr:"des journaux",       alts:["des journaux","les journaux"], needsHyphen:false, needsAccent:false, gender:"m", category:"plurals"},
    {en:"a newspaper",                     fr:"un journal",         alts:["un journal","le journal"], needsHyphen:false, needsAccent:false, gender:"m", guessGender:true, category:"plurals"},
    {en:"works / jobs (pl. of travail)",   fr:"des travaux",        alts:["des travaux","les travaux"], needsHyphen:false, needsAccent:false, gender:"m", category:"plurals"},
    {en:"a job / a piece of work",         fr:"un travail",         alts:["un travail","le travail"], needsHyphen:false, needsAccent:false, gender:"m", guessGender:true, category:"plurals"},
    {en:"municipal works (pl.)",           fr:"des travaux municipaux", alts:["des travaux municipaux"], needsHyphen:false, needsAccent:false, gender:"m", category:"plurals"},
    {en:"games (pl. of jeu)",              fr:"des jeux",           alts:["des jeux","les jeux"], needsHyphen:false, needsAccent:false, gender:"m", category:"plurals"},
    {en:"a game",                          fr:"un jeu",             alts:["un jeu","le jeu"],    needsHyphen:false, needsAccent:false, gender:"m", guessGender:true, category:"plurals"},
    {en:"beautiful hats (pl.)",            fr:"des beaux chapeaux", alts:["des beaux chapeaux"], needsHyphen:false, needsAccent:false, gender:"m", category:"plurals"},
    {en:"bad courses (pl.)",               fr:"des mauvais cours",  alts:["des mauvais cours","les mauvais cours"], needsHyphen:false, needsAccent:false, gender:"m", category:"plurals"},
    {en:"curious children (pl.)",          fr:"les enfants curieux",alts:["les enfants curieux","des enfants curieux"], needsHyphen:false, needsAccent:false, gender:"m", category:"plurals"},
    {en:"red noses (pl.)",                 fr:"des nez rouges",     alts:["des nez rouges","les nez rouges"], needsHyphen:false, needsAccent:false, gender:"m", category:"plurals"},
  ],
  categoryLabels: {
    all:"Random",
    classroom:"Classroom",
    useful:"Useful",
    identify:"Identifying",
    alphabet:"Alphabet",
    calendar:"Calendar",
    numbers:"Numbers",
    time:"Time",
    subjects:"Subjects",
    avoir:"Avoir",
    bodyparts:"Body parts",
    hair:"Hair",
    eyes:"Eyes",
    describe:"Describing",
    personality:"Personality",
    courses:"Courses",
    plurals:"Plurals",
    people:"People"
  }
};
